// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright 2022 NXP
 *
 * Peng Fan <peng.fan@nxp.com>
 */

#include <common.h>
#include <command.h>
#include <asm/arch/clock.h>
#include <asm/arch/sys_proto.h>
#include <asm/arch/ccm_regs.h>
#include <asm/global_data.h>

DECLARE_GLOBAL_DATA_PTR;

u32 clk_root_src[CLK_ROOT_NUM][4] = {
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		AUDIO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		AUDIO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		AUDIO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		AUDIO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		AUDIO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		AUDIO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		AUDIO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		AUDIO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		SYS_PLL_PFD0      },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		SYS_PLL_PFD0      },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		SYS_PLL_PFD0      },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		SYS_PLL_PFD0      },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		SYS_PLL_PFD0      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0,		SYS_PLL_PFD1,		SYS_PLL_PFD2      },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	SYS_PLL_PFD2_DIV2 },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	SYS_PLL_PFD2_DIV2 },
	{ OSC_24M_CLK,	AUDIO_PLL_CLK,		VIDEO_PLL_CLK,		EXT_CLK           },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	SYS_PLL_PFD2_DIV2 },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	SYS_PLL_PFD2_DIV2 },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     },
	{ OSC_24M_CLK,	SYS_PLL_PFD0_DIV2,	SYS_PLL_PFD1_DIV2,	VIDEO_PLL_CLK     } 
};

uint32_t oscpll_period[13] = {
    30517578, // 0  OSC_32K_CLK         0.03
    41666,    // 1  OSC_24M_CLK         24.00
    500,      // 2  ARM_PLL_CLK         2000.00
    1000,     // 3  SYS_PLL_PFD0        1000.00
    2000,     // 4  SYS_PLL_PFD0_DIV2   500.00
    1250,     // 5  SYS_PLL_PFD1        800.00
    2500,     // 6  SYS_PLL_PFD1_DIV2   400.00
    1600,     // 7  SYS_PLL_PFD2        625.00
    3200,     // 8  SYS_PLL_PFD2_DIV2   312.50
    1893,     // 9  AUDIO_PLL_CLK       528.00
    7518,     // 10 EXT_CLK             133.00
    1000,     // 11 DRAM_PLL_CLK        1000.00
    1785      // 12 VIDEO_PLL_CLK       560.00
};
