# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2013-2015, Freescale Semiconductor, Inc.

obj-y   += s32v234evb.o
obj-$(CONFIG_SJA1105) += sja1105_cfg.o

#########################################################################
