# Copyright 2015, Freescale Semiconductor
# Copyright 2017 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ipc.o
obj-y += svc/misc/rpc_clnt.o
obj-y += svc/pad/rpc_clnt.o
obj-y += svc/pm/rpc_clnt.o
obj-y += svc/rm/rpc_clnt.o
obj-y += svc/timer/rpc_clnt.o
