subdir-ccflags-y += -D_FILE_OFFSET_BITS=64 \
			-D_POSIX_C_SOURCE=199309L \
			-Wa,--noexecstack \
			-Werror \
			-Wall \
			-Wextra \
			-Wformat=2 \
			-Wno-psabi \
			-Wno-unused-parameter \
			-ffunction-sections \
			-std=gnu99
obj-y += libavb/
obj-y += libavb_ab/
obj-y += fsl/
