#
# Copyright 2017-2018 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

UBOOTINCLUDE += -I$(srctree)/drivers/video/imx/hdmi/hdp
obj-$(CONFIG_VIDEO_IMX_HDP_LOAD) += hdp_load.o hdprx_load.o hdp/
obj-$(CONFIG_VIDEO_IMX8M_HDMI) += imx8m_hdmi.o hdp/
