ifndef CONFIG_SPL_BUILD
obj-y += fsl_avb.o
endif

obj-y += fsl_avbkey.o
obj-y += utils.o
obj-y += fsl_bootctrl.o
obj-$(CONFIG_AVB_ATX) += fsl_atx_attributes.o
obj-$(CONFIG_AVB_WARNING_LOGO) += orange_warning_bmp_data.o
