#
# Copyright 2017 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= lowlevel_init.o
obj-y	+= soc.o clock_slice.o
obj-$(CONFIG_IMX8MQ) += clock_imx8mq.o
obj-$(CONFIG_IMX8MM) += clock_imx8mm.o
obj-$(CONFIG_VIDEO_IMXDCSS) += video_common.o

