# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_VIDEO_IPUV3) += mxc_ipuv3_fb.o ipu_common.o ipu_disp.o
obj-$(CONFIG_VIDEO_IMXDPUV1) += imxdpuv1.o imx8_dc.o
obj-$(CONFIG_VIDEO_IMX8_LVDS) += imx8_lvds.o
obj-$(CONFIG_VIDEO_IMX8M_DCSS) += imx8m_dcss.o
obj-$(CONFIG_VIDEO_SEC_MIPI_DSI) += sec_mipi_dsim.o
obj-$(CONFIG_VIDEO_IMX_SEC_DSI) += sec_dsim_imx.o
obj-$(CONFIG_VIDEO_IMX_LCDIFV3) += imx_lcdifv3.o
obj-$(CONFIG_VIDEO_NW_MIPI_DSI) += mipi_dsi_northwest.o
obj-$(CONFIG_VIDEO_IMX_NW_DSI) += nw_dsi_imx.o
obj-y += hdmi/
