#
# Copyright 2018 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += ddr3_phyinit_task.o
obj-y += ddr3_phyinit_train_sw_ffc_fw09.o
obj-y += ddr3_sw_fast_freq_chg_fw09.o
obj-y += restore_1d2d_trained_csr_ddr3_p012.o
obj-y += save_1d2d_trained_csr_ddr3_p012.o
endif
