#
# Copyright 2018 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += helper.o
obj-y += wait_ddrphy_training_complete.o
obj-$(CONFIG_TARGET_IMX8MM_DDR4_VAL) += ddr4/
endif
