#
# Copyright 2018 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += helper.o
obj-y += lpddr4_cfg_umctl2_m845.o
obj-y += lpddr4_phyinit_train_3000mts_fw09.o
obj-y += lpddr4_pmu_training_3000mts_fw09.o
obj-y += lpddr4_phyinit_task.o
endif
